# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@nchantdTree - Main@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@||
"""  #																			||
---  #																			||
<(META)>:  #																	||
	docid: '202520ac-28ad-4b1f-ac39-103a98d765b2'  #							||
	name: Nchantd Input#													||
	description: >  #															||
	expirary: <[expiration]>  #													||
	version: <[version]>  #														||
	authority: document|this  #													||
	security: sec|lvl2  #														||
	<(WT)>: -32  #																||
"""  # ||
# -*- coding: utf-8 -*-#														||
# =================================Core Modules==================================||
import sys

import logging
from os.path import abspath, dirname, join

logger = logging.getLogger(__name__)
import datetime as dt

# ===============================================================================||
from condor import condor  # ||
from ogma.logma import Logma

# ===============================================================================||
there = abspath(join(''))
here = join(dirname(__file__), '')
log = False
logma = Logma(__name__)

def leftClickSignalLog(signal, level=0) -> None:
	''' '''
	# logma.info(f'On Click this is the data provided {signal}, {signal.__dir__()}')
	# logma.info(f'Model {signal.model}')
	# logma.info(f'Model attributes {signal.model.__dir__()}')
	# logma.info(f'Row {signal.row()}')
	# logma.info(f'Sibling {signal.sibling(0, 1).data()}')
	# logma.info(f'Data {signal.data()}')
	# logma.info(f'Column {signal.column()}')
	# logma.info(f'Flags {signal.flags()}')
	# logma.info(f'internalId {signal.internalId()}')
	# logma.info(f'internalPointer {signal.internalPointer}')

def mousePressEventLog(event, level=0) -> None:
	''' '''
	if level >= 0:
		logma.info(f'Event {event.__dir__()}')
		logma.info(f'button {event.button()}')
		logma.info(f'buttons {event.buttons()}')
		logma.info(f'buttons {event.buttons().__dir__()}')
		logma.info(f'flags {event.flags()}')
		logma.info(f'flags {event.flags().__dir__()}')
		logma.info(f'globalPos {event.globalPos()}')
		logma.info(f'globalX {event.globalX()}')
		logma.info(f'globalY {event.globalY()}')
		logma.info(f'localPos {event.localPos()}')
		logma.info(f'screenPos {event.screenPos()}')
		logma.info(f'pos {event.pos()}')
		logma.info(f'source {event.source()}')
		logma.info(f'windowPos {event.windowPos()}')
		logma.info(f'x {event.x()}')
		logma.info(f'y {event.y()}')
		logma.info(f'modifiers {event.modifiers()}')
		logma.info(f'setTimestamp {event.setTimestamp(int(dt.datetime.timestamp(dt.datetime.now())))}')
		logma.info(f'timestamp {event.timestamp()}')
	if level >= 1:
		logma.info(f'Type {event.Type()}')
		logma.info(f'accept {event.accept()}')
		logma.info(f'ignore {event.ignore()}')
		logma.info(f'isAccepted {event.isAccepted()}')
		logma.info(f'registerEventType {event.registerEventType()}')
		logma.info(f'setAccepted {event.setAccepted(False)}')
		logma.info(f'spontaneous {event.spontaneous()}')
		logma.info(f'type {event.type()}')
		logma.info(f'ActionAdded {event.ActionAdded}')
		logma.info(f'ActionChanged {event.ActionChanged}')
		logma.info(f'ActionRemoved {event.ActionRemoved}')
		logma.info(f'ActivationChange {event.ActivationChange}')
		logma.info(f'ApplicationActivate {event.ApplicationActivate}')
		logma.info(f'ApplicationActivated {event.ApplicationActivated}')
		# logma.info(f'ApplicationDeactivate {}', event.ApplicationDeactivate)
		# logma.info(f'ApplicationDeactivated {}', event.ApplicationDeactivated)
		# logma.info(f'ApplicationFontChange {}', event.ApplicationFontChange)
		# logma.info(f'ApplicationLayoutDirectionChange {}', event.ApplicationLayoutDirectionChange)
		# logma.info(f'ApplicationPaletteChange {}', event.ApplicationPaletteChange)
		# logma.info(f'ApplicationStateChange {}', event.ApplicationStateChange)
		# logma.info(f'ApplicationWindowIconChange {}', event.ApplicationWindowIconChange)
		# logma.info(f'ChildAdded {}', event.ChildAdded)
		# logma.info(f'ChildPolished {}', event.ChildPolished)
		# logma.info(f'ChildRemoved {}', event.ChildRemoved)
		# logma.info(f'Clipboard {}', event.Clipboard)
		# logma.info(f'Close {}', event.Close)
		# logma.info(f'CloseSoftwareInputPanel {}', event.CloseSoftwareInputPanel)
		# logma.info(f'ContentsRectChange {}', event.ContentsRectChange)
		# logma.info(f'ContextMenu {}', event.ContextMenu)
		# logma.info(f'CursorChange {}', event.CursorChange)
		# logma.info(f'DeferredDelete {}', event.DeferredDelete)
		# logma.info(f'DragEnter', event.DragEnter)
		# logma.info(f'DragLeave', event.DragLeave)
		# logma.info(f'DragMove', event.DragMove)
		# logma.info(f'Drop', event.Drop)
		# logma.info(f'DynamicPropertyChange', event.DynamicPropertyChange)
		# logma.info(f'EnabledChange', event.EnabledChange)
		# logma.info(f'Enter', event.Enter)
		# logma.info(f'EnterWhatsThisMode', event.EnterWhatsThisMode)
		# logma.info(f'Expose', event.Expose)
		# logma.info(f'FileOpen', event.FileOpen)
		# logma.info(f'FocusAboutToChange', event.FocusAboutToChange)
		# logma.info(f'FocusIn', event.FocusIn)
		# logma.info(f'FocusOut', event.FocusOut)
		# logma.info(f'FontChange', event.FontChange)
		# logma.info(f'Gesture', event.Gesture)
		# logma.info(f'GestureOverride', event.GestureOverride)
		# logma.info(f'GrabKeyboard', event.GrabKeyboard)
		# logma.info(f'GrabMouse', event.GrabMouse)
		# logma.info(f'GraphicsSceneContextMenu', event.GraphicsSceneContextMenu)
		# logma.info(f'GraphicsSceneDragEnter', event.GraphicsSceneDragEnter)
		# logma.info(f'GraphicsSceneDragLeave', event.GraphicsSceneDragLeave)
		# logma.info(f'GraphicsSceneDragMove', event.GraphicsSceneDragMove)
		# logma.info(f'GraphicsSceneDrop', event.GraphicsSceneDrop)
		# logma.info(f'GraphicsSceneHelp', event.GraphicsSceneHelp)
		# logma.info(f'GraphicsSceneHoverEnter', event.GraphicsSceneHoverEnter)
		# logma.info(f'GraphicsSceneHoverLeave', event.GraphicsSceneHoverLeave)
		# logma.info(f'GraphicsSceneHoverMove', event.GraphicsSceneHoverMove)
		# logma.info(f'GraphicsSceneMouseDoubleClick', event.GraphicsSceneMouseDoubleClick)
		# logma.info(f'GraphicsSceneMouseMove', event.GraphicsSceneMouseMove)
		# logma.info(f'GraphicsSceneMousePress', event.GraphicsSceneMousePress)
		# logma.info(f'GraphicsSceneMouseRelease', event.GraphicsSceneMouseRelease)
		# logma.info(f'GraphicsSceneMove', event.GraphicsSceneMove)
		# logma.info(f'GraphicsSceneResize', event.GraphicsSceneResize)
		# logma.info(f'GraphicsSceneWheel', event.GraphicsSceneWheel)
		# logma.info(f'Hide', event.Hide)
		# logma.info(f'HideToParent', event.HideToParent)
		# logma.info(f'HoverEnter', event.HoverEnter)
		# logma.info(f'HoverLeave', event.HoverLeave)
		# logma.info(f'HoverMove', event.HoverMove)
		# logma.info(f'IconDrag', event.IconDrag)
		# logma.info(f'IconTextChange', event.IconTextChange)
		# logma.info(f'InputMethod', event.InputMethod)
		# logma.info(f'InputMethodQuery', event.InputMethodQuery)
		# logma.info(f'KeyPress', event.KeyPress)
		# logma.info(f'KeyRelease', event.KeyRelease)
		# logma.info(f'KeyboardLayoutChange', event.KeyboardLayoutChange)
		# logma.info(f'LanguageChange', event.LanguageChange)
		# logma.info(f'LayoutDirectionChange', event.LayoutDirectionChange)
		# logma.info(f'LayoutRequest', event.LayoutRequest)
		# logma.info(f'Leave', event.Leave)
		# logma.info(f'LeaveWhatsThisMode', event.LeaveWhatsThisMode)
		# logma.info(f'LocaleChange', event.LocaleChange)
		# logma.info(f'MacSizeChange', event.MacSizeChange)
		# logma.info(f'MaxUser', event.MaxUser)
		# logma.info(f'MetaCall', event.MetaCall)
		# logma.info(f'ModifiedChange', event.ModifiedChange)
		# logma.info(f'MouseButtonDblClick', event.MouseButtonDblClick)
		# logma.info(f'MouseButtonPress', event.MouseButtonPress)
		# logma.info(f'MouseButtonRelease', event.MouseButtonRelease)
		# logma.info(f'MouseMove', event.MouseMove)
		# logma.info(f'MouseTrackingChange', event.MouseTrackingChange)
		# logma.info(f'Move', event.Move)
		# logma.info(f'NonClientAreaMouseButtonDblClick', event.NonClientAreaMouseButtonDblClick)
		# logma.info(f'NonClientAreaMouseButtonPress', event.NonClientAreaMouseButtonPress)
		# logma.info(f'NonClientAreaMouseButtonRelease', event.NonClientAreaMouseButtonRelease)
		# logma.info(f'NonClientAreaMouseMove', event.NonClientAreaMouseMove)
		# logma.info(f'None_', event.None_)
		# logma.info(f'OkRequest', event.OkRequest)
		# logma.info(f'OrientationChange', event.OrientationChange)
		# logma.info(f'Paint', event.Paint)
		# logma.info(f'PaletteChange', event.PaletteChange)
		# logma.info(f'ParentAboutToChange', event.ParentAboutToChange)
		# logma.info(f'ParentChange', event.ParentChange)
		# logma.info(f'PlatformPanel', event.PlatformPanel)
		# logma.info(f'PlatformSurface', event.PlatformSurface)
		# logma.info(f'Polish', event.Polish)
		# logma.info(f'PolishRequest', event.PolishRequest)
		# logma.info(f'QueryWhatsThis', event.QueryWhatsThis)
		# logma.info(f'ReadOnlyChange', event.ReadOnlyChange)
		# logma.info(f'RequestSoftwareInputPanel', event.RequestSoftwareInputPanel)
		# logma.info(f'Resize', event.Resize)
		# logma.info(f'Scroll', event.Scroll)
		# logma.info(f'ScrollPrepare', event.ScrollPrepare)
		# logma.info(f'Shortcut', event.Shortcut)
		# logma.info(f'ShortcutOverride', event.ShortcutOverride)
		# logma.info(f'Show', event.Show)
		# logma.info(f'ShowToParent', event.ShowToParent)
		# logma.info(f'SockAct', event.SockAct)
		# logma.info(f'StateMachineSignal', event.StateMachineSignal)
		# logma.info(f'StateMachineWrapped', event.StateMachineWrapped)
		# logma.info(f'StatusTip', event.StatusTip)
		# logma.info(f'StyleChange', event.StyleChange)
		# logma.info(f'TabletEnterProximity', event.TabletEnterProximity)
		# logma.info(f'TabletLeaveProximity', event.TabletLeaveProximity)
		# logma.info(f'TabletMove', event.TabletMove)
		# logma.info(f'TabletPress', event.TabletPress)
		# logma.info(f'TabletRelease', event.TabletRelease)
		# logma.info(f'TabletTrackingChange', event.TabletTrackingChange)
		# logma.info(f'ThreadChange', event.ThreadChange)
		# logma.info(f'Timer', event.Timer)
		# logma.info(f'ToolBarChange', event.ToolBarChange)
		# logma.info(f'ToolTip', event.ToolTip)
		# logma.info(f'ToolTipChange', event.ToolTipChange)
		# logma.info(f'TouchBegin', event.TouchBegin)
		# logma.info(f'TouchCancel', event.TouchCancel)
		# logma.info(f'TouchEnd', event.TouchEnd)
		# logma.info(f'TouchUpdate', event.TouchUpdate)
		# logma.info(f'UngrabKeyboard', event.UngrabKeyboard)
		# logma.info(f'UngrabMouse', event.UngrabMouse)
		# logma.info(f'UpdateLater', event.UpdateLater)
		# logma.info(f'UpdateRequest', event.UpdateRequest)
		# logma.info(f'User', event.User)
		# logma.info(f'WhatsThis', event.WhatsThis)
		# logma.info(f'WhatsThisClicked', event.WhatsThisClicked)
		# logma.info(f'Wheel', event.Wheel)
		# logma.info(f'WinEventAct', event.WinEventAct)
		# logma.info(f'WinIdChange', event.WinIdChange)
		# logma.info(f'WindowActivate', event.WindowActivate)
		# logma.info(f'WindowBlocked', event.WindowBlocked)
		# logma.info(f'WindowDeactivate', event.WindowDeactivate)
		# logma.info(f'WindowIconChange', event.WindowIconChange)
		# logma.info(f'WindowStateChange', event.WindowStateChange)
		# logma.info(f'WindowTitleChange', event.WindowTitleChange)
		# logma.info(f'WindowUnblocked', event.WindowUnblocked)
		# logma.info(f'ZOrderChange', event.ZOrderChange)
